<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="UDIND-LP044" ignored="2" name="Default test(failed)(failed)" tests="4" failures="1" timestamp="15 Jun 2022 03:53:02 GMT" time="0.041" errors="0">
  <testcase name="test3" time="0.011" classname="Demo.TestNGFailedDemo">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="Demo.TestNGFailedDemo">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="Demo.TestNGFailedDemo">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="Demo.TestNGFailedDemo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Demo.TestNGFailedDemo.test3(TestNGFailedDemo.java:23)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.0" classname="Demo.TestNGFailedDemo">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.0" classname="Demo.TestNGFailedDemo">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed)(failed) -->
